export interface LogEntry {
  level: string | number;
  time: string;
  category: string;
  msg: string;
  // Axiom API 응답 필드
  '@app.next-axiom-version'?: string;
  _sysTime?: string;
  'fields.aplQuery'?: string | null;
  'fields.columns'?: any[] | null;
  'fields.dataset'?: string | null;
  'fields.error'?: any;
  'fields.fields'?: any[] | null;
  'fields.firstTable.columns'?: any[] | null;
  'fields.firstTable.fields'?: any[] | null;
  'fields.firstTable.groups'?: any[] | null;
  'fields.firstTable.name'?: string | null;
  'fields.firstTable.order'?: any[] | null;
  'fields.firstTable.range.end'?: string | null;
  'fields.firstTable.range.field'?: string | null;
  'fields.firstTable.range.start'?: string | null;
  'fields.firstTable.sources'?: any[] | null;
  'fields.firstTableKeys'?: any[] | null;
  'fields.keys'?: any[] | null;
  'fields.logCount'?: number | null;
  'fields.page'?: number | null;
  'fields.pageSize'?: number | null;
  'fields.request_id'?: string | null;
  'fields.response.datasetNames'?: any[] | null;
  'fields.response.format'?: string | null;
  'fields.response.status.blocksCached'?: number | null;
  'fields.response.status.blocksExamined'?: number | null;
  'fields.response.status.blocksMatched'?: number | null;
  'fields.response.status.blocksSkipped'?: number | null;
  'fields.response.status.cacheStatus'?: number | null;
  'fields.response.status.elapsedTime'?: number | null;
  'fields.response.status.isPartial'?: boolean | null;
  'fields.response.status.maxBlockTime'?: string | null;
  'fields.response.status.maxCursor'?: string | null;
  'fields.response.status.minBlockTime'?: string | null;
  'fields.response.status.minCursor'?: string | null;
  'fields.response.status.numGroups'?: number | null;
  'fields.response.status.rowsExamined'?: number | null;
  'fields.response.status.rowsMatched'?: number | null;
  'fields.response.tables'?: any[] | null;
  'fields.source'?: string | null;
  'fields.status'?: any;
  'fields.tables'?: any[] | null;
  'fields.tablesLength'?: number | null;
  'fields.tablesType'?: string | null;
  'fields.totalRows'?: number | null;
  'fields.url'?: string | null;
  'fields.request'?: any;
  message?: string;
  path?: any;
  'platform.environment'?: string;
  'platform.route'?: any;
  'platform.source'?: string;
  'request.durationMs'?: any;
  'request.endTime'?: any;
  'request.host'?: string;
  'request.ip'?: any;
  'request.method'?: string;
  'request.path'?: string;
  'request.referer'?: string;
  'request.region'?: any;
  'request.scheme'?: string;
  'request.startTime'?: any;
  'request.statusCode'?: any;
  'request.userAgent'?: string;
  source?: string;
  'webVital.delta'?: any;
  'webVital.entries'?: any;
  'webVital.id'?: any;
  'webVital.name'?: any;
  'webVital.navigationType'?: any;
  'webVital.rating'?: any;
  'webVital.value'?: any;
  [key: string]: any;
}